import type { ComponentTemplate } from './types';

export const COMPONENT_TEMPLATES: ComponentTemplate[] = [
  {
    id: 'tpl_table',
    type: 'table',
    name: 'Table',
    description: 'Basic data table with headers and rows',
    width: 400,
    height: 250,
    elements: [
      // Container
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 0,
        width: 400,
        height: 250,
        semanticTag: 'section',
        description: 'Table container',
      },
      // Header row background
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 0,
        width: 400,
        height: 40,
      },
      // Column headers
      {
        type: 'text',
        offsetX: 10,
        offsetY: 10,
        width: 120,
        height: 20,
        content: 'Name',
      },
      {
        type: 'text',
        offsetX: 140,
        offsetY: 10,
        width: 120,
        height: 20,
        content: 'Status',
      },
      {
        type: 'text',
        offsetX: 270,
        offsetY: 10,
        width: 120,
        height: 20,
        content: 'Date',
      },
      // Divider line
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 40,
        width: 400,
        height: 2,
      },
      // Row 1
      {
        type: 'text',
        offsetX: 10,
        offsetY: 55,
        width: 120,
        height: 20,
        content: 'Item 1',
      },
      {
        type: 'text',
        offsetX: 140,
        offsetY: 55,
        width: 120,
        height: 20,
        content: 'Active',
      },
      {
        type: 'text',
        offsetX: 270,
        offsetY: 55,
        width: 120,
        height: 20,
        content: '2024-01-15',
      },
      // Row 2
      {
        type: 'text',
        offsetX: 10,
        offsetY: 85,
        width: 120,
        height: 20,
        content: 'Item 2',
      },
      {
        type: 'text',
        offsetX: 140,
        offsetY: 85,
        width: 120,
        height: 20,
        content: 'Inactive',
      },
      {
        type: 'text',
        offsetX: 270,
        offsetY: 85,
        width: 120,
        height: 20,
        content: '2024-01-14',
      },
      // Row 3
      {
        type: 'text',
        offsetX: 10,
        offsetY: 115,
        width: 120,
        height: 20,
        content: 'Item 3',
      },
      {
        type: 'text',
        offsetX: 140,
        offsetY: 115,
        width: 120,
        height: 20,
        content: 'Active',
      },
      {
        type: 'text',
        offsetX: 270,
        offsetY: 115,
        width: 120,
        height: 20,
        content: '2024-01-13',
      },
      // Pagination
      {
        type: 'text',
        offsetX: 10,
        offsetY: 220,
        width: 150,
        height: 20,
        content: 'Showing 1-10 of 100',
      },
    ],
  },
  {
    id: 'tpl_table_filters',
    type: 'table-filters',
    name: 'Table + Filters',
    description: 'Data table with filter controls',
    width: 400,
    height: 320,
    elements: [
      // Filter row background
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 0,
        width: 400,
        height: 50,
      },
      // Search input
      {
        type: 'rectangle',
        offsetX: 10,
        offsetY: 12,
        width: 200,
        height: 28,
        semanticTag: 'input',
        description: 'Search filter',
      },
      {
        type: 'text',
        offsetX: 15,
        offsetY: 18,
        width: 50,
        height: 20,
        content: 'Search...',
      },
      // Status filter
      {
        type: 'rectangle',
        offsetX: 220,
        offsetY: 12,
        width: 90,
        height: 28,
        semanticTag: 'button',
        description: 'Status filter dropdown',
      },
      {
        type: 'text',
        offsetX: 225,
        offsetY: 18,
        width: 60,
        height: 20,
        content: 'Status ▼',
      },
      // Reset button
      {
        type: 'rectangle',
        offsetX: 320,
        offsetY: 12,
        width: 70,
        height: 28,
        semanticTag: 'button',
        description: 'Clear filters',
      },
      {
        type: 'text',
        offsetX: 335,
        offsetY: 18,
        width: 40,
        height: 20,
        content: 'Reset',
      },
      // Table container
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 60,
        width: 400,
        height: 250,
        semanticTag: 'section',
        description: 'Table container',
      },
      // Header row background
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 60,
        width: 400,
        height: 40,
      },
      // Column headers
      {
        type: 'text',
        offsetX: 10,
        offsetY: 70,
        width: 120,
        height: 20,
        content: 'Name',
      },
      {
        type: 'text',
        offsetX: 140,
        offsetY: 70,
        width: 120,
        height: 20,
        content: 'Status',
      },
      {
        type: 'text',
        offsetX: 270,
        offsetY: 70,
        width: 120,
        height: 20,
        content: 'Date',
      },
      // Divider
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 100,
        width: 400,
        height: 2,
      },
      // Row 1
      {
        type: 'text',
        offsetX: 10,
        offsetY: 115,
        width: 120,
        height: 20,
        content: 'Item 1',
      },
      {
        type: 'text',
        offsetX: 140,
        offsetY: 115,
        width: 120,
        height: 20,
        content: 'Active',
      },
      {
        type: 'text',
        offsetX: 270,
        offsetY: 115,
        width: 120,
        height: 20,
        content: '2024-01-15',
      },
      // Row 2
      {
        type: 'text',
        offsetX: 10,
        offsetY: 145,
        width: 120,
        height: 20,
        content: 'Item 2',
      },
      {
        type: 'text',
        offsetX: 140,
        offsetY: 145,
        width: 120,
        height: 20,
        content: 'Inactive',
      },
      {
        type: 'text',
        offsetX: 270,
        offsetY: 145,
        width: 120,
        height: 20,
        content: '2024-01-14',
      },
    ],
  },
  {
    id: 'tpl_empty_state',
    type: 'empty-state',
    name: 'Empty State',
    description: 'Placeholder for empty data state',
    width: 300,
    height: 200,
    elements: [
      // Container
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 0,
        width: 300,
        height: 200,
        semanticTag: 'section',
        description: 'Empty state container',
      },
      // Icon placeholder
      {
        type: 'rectangle',
        offsetX: 125,
        offsetY: 30,
        width: 50,
        height: 50,
      },
      // Headline
      {
        type: 'text',
        offsetX: 80,
        offsetY: 100,
        width: 140,
        height: 20,
        content: 'No items yet',
      },
      // Description
      {
        type: 'text',
        offsetX: 40,
        offsetY: 130,
        width: 220,
        height: 20,
        content: 'Get started by adding an item',
      },
      // CTA button
      {
        type: 'rectangle',
        offsetX: 100,
        offsetY: 160,
        width: 100,
        height: 30,
        semanticTag: 'button',
        description: 'Add first item',
      },
      {
        type: 'text',
        offsetX: 115,
        offsetY: 168,
        width: 70,
        height: 20,
        content: 'Add Item',
      },
    ],
  },
  {
    id: 'tpl_confirmation_modal',
    type: 'confirmation-modal',
    name: 'Confirmation Modal',
    description: 'Dialog for confirming destructive actions',
    width: 350,
    height: 180,
    elements: [
      // Modal background
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 0,
        width: 350,
        height: 180,
        semanticTag: 'section',
        description: 'Confirmation modal',
      },
      // Header
      {
        type: 'text',
        offsetX: 20,
        offsetY: 20,
        width: 200,
        height: 20,
        content: 'Confirm Action',
      },
      // Close button
      {
        type: 'rectangle',
        offsetX: 315,
        offsetY: 15,
        width: 20,
        height: 20,
        semanticTag: 'button',
        description: 'Close modal',
      },
      {
        type: 'text',
        offsetX: 320,
        offsetY: 18,
        width: 10,
        height: 15,
        content: '×',
      },
      // Divider
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 50,
        width: 350,
        height: 1,
      },
      // Message line 1
      {
        type: 'text',
        offsetX: 20,
        offsetY: 70,
        width: 310,
        height: 20,
        content: 'Are you sure you want to delete this?',
      },
      // Message line 2
      {
        type: 'text',
        offsetX: 20,
        offsetY: 95,
        width: 310,
        height: 20,
        content: 'This action cannot be undone.',
      },
      // Footer divider
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 130,
        width: 350,
        height: 1,
      },
      // Cancel button
      {
        type: 'rectangle',
        offsetX: 170,
        offsetY: 140,
        width: 80,
        height: 32,
        semanticTag: 'button',
        description: 'Cancel action',
      },
      {
        type: 'text',
        offsetX: 188,
        offsetY: 148,
        width: 44,
        height: 20,
        content: 'Cancel',
      },
      // Confirm button
      {
        type: 'rectangle',
        offsetX: 260,
        offsetY: 140,
        width: 80,
        height: 32,
        semanticTag: 'button',
        description: 'Confirm deletion',
      },
      {
        type: 'text',
        offsetX: 278,
        offsetY: 148,
        width: 44,
        height: 20,
        content: 'Delete',
      },
    ],
  },
  {
    id: 'tpl_simple_form',
    type: 'simple-form',
    name: 'Simple Form',
    description: 'Basic form with inputs and submit',
    width: 350,
    height: 280,
    elements: [
      // Form container
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 0,
        width: 350,
        height: 280,
        semanticTag: 'section',
        description: 'Form container',
      },
      // Title
      {
        type: 'text',
        offsetX: 20,
        offsetY: 20,
        width: 150,
        height: 20,
        content: 'Create New Item',
      },
      // Name field label
      {
        type: 'text',
        offsetX: 20,
        offsetY: 60,
        width: 50,
        height: 16,
        content: 'Name',
      },
      {
        type: 'rectangle',
        offsetX: 20,
        offsetY: 82,
        width: 310,
        height: 36,
        semanticTag: 'input',
        description: 'Name input field',
      },
      // Email field label
      {
        type: 'text',
        offsetX: 20,
        offsetY: 130,
        width: 50,
        height: 16,
        content: 'Email',
      },
      {
        type: 'rectangle',
        offsetX: 20,
        offsetY: 152,
        width: 310,
        height: 36,
        semanticTag: 'input',
        description: 'Email input field',
      },
      // Description label
      {
        type: 'text',
        offsetX: 20,
        offsetY: 200,
        width: 80,
        height: 16,
        content: 'Description',
      },
      {
        type: 'rectangle',
        offsetX: 20,
        offsetY: 222,
        width: 310,
        height: 36,
        semanticTag: 'input',
        description: 'Description input',
      },
      // Divider
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 265,
        width: 350,
        height: 1,
      },
    ],
  },
  {
    id: 'tpl_action_footer',
    type: 'action-footer',
    name: 'Action Footer',
    description: 'Primary and secondary action buttons',
    width: 350,
    height: 60,
    elements: [
      // Footer background
      {
        type: 'rectangle',
        offsetX: 0,
        offsetY: 0,
        width: 350,
        height: 60,
        semanticTag: 'section',
        description: 'Action footer',
      },
      // Secondary button
      {
        type: 'rectangle',
        offsetX: 170,
        offsetY: 14,
        width: 80,
        height: 32,
        semanticTag: 'button',
        description: 'Secondary action',
      },
      {
        type: 'text',
        offsetX: 188,
        offsetY: 22,
        width: 44,
        height: 20,
        content: 'Cancel',
      },
      // Primary button
      {
        type: 'rectangle',
        offsetX: 260,
        offsetY: 14,
        width: 80,
        height: 32,
        semanticTag: 'button',
        description: 'Primary action',
      },
      {
        type: 'text',
        offsetX: 283,
        offsetY: 22,
        width: 34,
        height: 20,
        content: 'Save',
      },
    ],
  },
];
